{
  ["outline"] = "OUTLINE",
  ["authorOptions"] = {
      [1] = {
          ["fontSize"] = "large",
          ["type"] = "description",
          ["text"] = "Auto-Mark Options",
          ["width"] = 1,
      },
      [2] = {
          ["type"] = "toggle",
          ["key"] = "isRaidEnabled",
          ["useDesc"] = false,
          ["name"] = "Enable Raid Marks",
          ["default"] = true,
          ["width"] = 1.4,
      },
      [3] = {
          ["type"] = "toggle",
          ["useDesc"] = false,
          ["key"] = "isPartyEnabled",
          ["default"] = true,
          ["name"] = "Enable Party Marks",
          ["width"] = 1.4,
      },
      [4] = {
          ["useName"] = false,
          ["type"] = "header",
          ["text"] = "",
          ["noMerge"] = false,
          ["width"] = 1.4,
      },
      [5] = {
          ["type"] = "toggle",
          ["useDesc"] = false,
          ["key"] = "isMarkingTanks",
          ["default"] = true,
          ["name"] = "Mark Tanks",
          ["width"] = 1.5,
      },
      [6] = {
          ["type"] = "select",
          ["key"] = "tankMarker1",
          ["values"] = {
              [1] = "|cFFFFF100Star",
              [2] = "|cFFFF9000Circle",
              [3] = "|cFFFF00FFDiamond",
              [4] = "|cFF00FF00Triangle",
              [5] = "|cFFFFFFFFCrescent",
              [6] = "|cFF00B3FFSquare",
              [7] = "|cFFFF0000X",
              [8] = "|cFFFFFFFFSkull",
          },
          ["useDesc"] = false,
          ["name"] = "Tank 1",
          ["default"] = 2,
          ["width"] = 1.4,
      },
      [7] = {
          ["type"] = "select",
          ["values"] = {
              [1] = "|cFFFFF100Star",
              [2] = "|cFFFF9000Circle",
              [3] = "|cFFFF00FFDiamond",
              [4] = "|cFF00FF00Triangle",
              [5] = "|cFFFFFFFFCrescent",
              [6] = "|cFF00B3FFSquare",
              [7] = "|cFFFF0000X",
              [8] = "|cFFFFFFFFSkull",
          },
          ["key"] = "tankMarker2",
          ["default"] = 3,
          ["name"] = "Tank 2",
          ["useDesc"] = false,
          ["width"] = 1.4,
      },
  },
  ["displayText"] = "\\n",
  ["shadowYOffset"] = -1,
  ["anchorPoint"] = "CENTER",
  ["displayText_format_p_time_format"] = 0,
  ["customTextUpdate"] = "event",
  ["automaticWidth"] = "Auto",
  ["actions"] = {
      ["start"] = {
          ["do_custom"] = true,
          ["custom"] = "if (aura_env.config.isMarkingTanks) then\\n    aura_env.SetTankMarkers()\\nend\\n",
      },
      ["init"] = {
          ["do_custom"] = true,
          ["custom"] = "aura_env.addIfTank = function(unit, tankTable)\\n    local role = UnitGroupRolesAssigned(unit)\\n\\n    if role == 'TANK' and UnitExists(unit) then table.insert(tankTable, unit) end\\n\\n    return tankTable\\nend\\n\\naura_env.getTanks = function()\\n    local tanks = {}\\n    local groupType = IsInRaid() and \\\"raid\\\" or \\\"party\\\"\\n\\n    for i = 1, GetNumGroupMembers() do\\n        local unitId = groupType .. i\\n\\n        tanks = aura_env.addIfTank(unitId, tanks)\\n    end\\n\\n    if (groupType == \\\"party\\\") then\\n        -- The player is not included in \\\"party\\\"\\n        tanks = aura_env.addIfTank(\\\"player\\\", tanks)\\n    end\\n\\n    return tanks\\nend\\n\\naura_env.SetTankMarkers = function()\\n    local tanks = aura_env.getTanks()\\n\\n    for i, tank in pairs(tanks) do\\n        local configKey = \\\"tankMarker\\\" .. i\\n        local markerNumber = aura_env.config[configKey]\\n\\n        SetRaidTarget(tank, markerNumber)\\n    end\\nend\\n",
      },
      ["finish"] = {
      },
  },
  ["triggers"] = {
      [1] = {
          ["trigger"] = {
              ["use_alwaystrue"] = true,
              ["use_genericShowOn"] = true,
              ["genericShowOn"] = "showOnCooldown",
              ["subeventPrefix"] = "SPELL",
              ["message_operator"] = "find('%s')",
              ["unit"] = "player",
              ["names"] = {
              },
              ["text_operator"] = "find('%s')",
              ["debuffType"] = "HELPFUL",
              ["spellName"] = 0,
              ["type"] = "unit",
              ["use_absorbHealMode"] = true,
              ["subeventSuffix"] = "_CAST_START",
              ["use_text"] = true,
              ["text"] = "Pull",
              ["event"] = "Conditions",
              ["use_dbmType"] = false,
              ["realSpellName"] = 0,
              ["use_spellName"] = true,
              ["spellIds"] = {
              },
              ["message"] = "pull",
              ["use_message"] = true,
              ["use_unit"] = true,
              ["use_track"] = true,
              ["use_absorbMode"] = true,
          },
          ["untrigger"] = {
          },
      },
      ["disjunctive"] = "any",
      ["activeTriggerMode"] = -10,
  },
  ["displayText_format_p_format"] = "timed",
  ["internalVersion"] = 51,
  ["selfPoint"] = "BOTTOM",
  ["desc"] = "Auto-Mark Tanks on DBM/BW Pull Timer",
  ["font"] = "Friz Quadrata TT",
  ["subRegions"] = {
      [1] = {
          ["type"] = "subbackground",
      },
  },
  ["load"] = {
      ["ingroup"] = {
          ["multi"] = {
              ["group"] = true,
              ["raid"] = true,
          },
      },
      ["use_zoneIds"] = false,
      ["talent"] = {
          ["multi"] = {
          },
      },
      ["spec"] = {
          ["multi"] = {
          },
      },
      ["use_encounterid"] = false,
      ["use_ingroup"] = false,
      ["use_instance_type"] = false,
      ["zoneIds"] = "g427",
      ["encounterid"] = "2512, 2542, 2553, 2540, 2544, 2539, 2529, 2546, 2543, 2549, 2537",
      ["class"] = {
          ["multi"] = {
          },
      },
      ["instance_type"] = {
          ["multi"] = {
              [1] = true,
              [2] = true,
              [17] = true,
              [8] = true,
              [16] = true,
              [14] = true,
              [23] = true,
              [15] = true,
          },
      },
      ["size"] = {
          ["multi"] = {
              ["ten"] = true,
              ["party"] = true,
              ["twenty"] = true,
              ["twentyfive"] = true,
          },
      },
  },
  ["authorMode"] = true,
  ["fontSize"] = 30,
  ["shadowXOffset"] = 1,
  ["regionType"] = "text",
  ["displayText_format_p_time_precision"] = 1,
  ["displayText_format_p_time_dynamic_threshold"] = 60,
  ["animation"] = {
      ["start"] = {
          ["type"] = "none",
          ["easeStrength"] = 3,
          ["duration_type"] = "seconds",
          ["easeType"] = "none",
      },
      ["main"] = {
          ["type"] = "none",
          ["easeStrength"] = 3,
          ["duration_type"] = "seconds",
          ["easeType"] = "none",
      },
      ["finish"] = {
          ["type"] = "none",
          ["easeStrength"] = 3,
          ["duration_type"] = "seconds",
          ["easeType"] = "none",
      },
  },
  ["fixedWidth"] = 200,
  ["justify"] = "LEFT",
  ["color"] = {
      [1] = 1,
      [2] = 1,
      [3] = 1,
      [4] = 1,
  },
  ["id"] = "Auto-Mark Tanks",
  ["yOffset"] = 0,
  ["frameStrata"] = 1,
  ["anchorFrameType"] = "SCREEN",
  ["xOffset"] = -1010,
  ["config"] = {
      ["isRaidEnabled"] = true,
      ["isPartyEnabled"] = true,
      ["isMarkingTanks"] = true,
      ["tankMarker2"] = 7,
      ["tankMarker1"] = 6,
  },
  ["uid"] = "sNj)vd)PbYL",
  ["wordWrap"] = "WordWrap",
  ["shadowColor"] = {
      [1] = 0,
      [2] = 0,
      [3] = 0,
      [4] = 1,
  },
  ["conditions"] = {
  },
  ["information"] = {
  },
  ["url"] = "https://wago.io/-Pf1AYz8M",
}